openapi: 3.0.0
info:
  title: Smeup Provider API
  description: Smeup Provider API (only for fun)
  version: 0.0.1
servers:
  - url: ${contextPath}/api/
paths:
  /fun:
    post:
      operationId: invoke
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                fun:
                  type: string
              required:
                - fun
      responses:
        default:
          description: no description
  /AuthenticateService:
    post:
      operationId: login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                usr:
                  type: string
                pwd:
                  type: string
                env:
                  type: string
                ccsid:
                  type: integer
                  default: 1144
              required:
                - usr
                - pwd
                - env
      responses:
        default:
          description: no description
  /DisconnectService:
    delete:
      operationId: logout
      responses:
        default:
          description: no description
          